version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/cie-react
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
